### ISSUE TITLE
Use Stock Kernel

### ISSUE THREAD

**Issue by ghost** [SailfishOS-SonyXperia/bugs#20]
Hi wouldn't it be better to use stock kernel than SODP kernel, you could use https://github.com/XperiaBrickers/android_kernel_sony_sm8250/tree/custom

**Comment by Thaodan** [comment]
Hey, please open a bug at https://github.com/SailfishOS-SonyXperia/bugs unless you have specific issue with this package.

**Comment by Thaodan** [comment]
I moved the bug now, no need to create a separate issue.

**Comment by Thaodan** [comment]
Why would it be better?

The issue with using the stock kernel is that it is supposed to be used with the stock blobs which is a nogo since it won't work for AOSP.
Also the AOSP kernel is maintained better

**Comment by ghost** [comment]
It wouldn't rely on using sodp vendor, the kernel works with also just fine, ive been building ROMs using this

**Comment by Thaodan** [comment]
You can't really publish the stock roms vendor image unless you have the 
permissions to distribute Sony's and Qualcomms binaries.

**Comment by ghost** [comment]
Hmm ok, understood
