### ISSUE TITLE
[BUG][Kumano][Xperia 5 J9210][SailfishOS-4.4.0.68]: Only 1SIM is available.

### ISSUE THREAD

**Issue by VZuyev** [SailfishOS-SonyXperia/bugs#51]
### Environment

```markdown
- **Platform: Kumano
- **Device: Xperia 5 J9210
- **Sailfish OS Version: 4.4.0.68
- **Kernel version: 4.14
- **Droid-Hal Version: 10
- **Droid-System Version: 10
- **Software binaries version: SW_binaries_for_Xperia_Android_10.0.7.1_r1_v12a_kumano
```

### Previously working on

```markdown
Sailfish_OS-Sailfish-SonyXperia-4.4.0.68-j9210-1.0.0.6
```

### Description

Only 1SIM is available. 2SIM should be.

### Symptoms

Only 1SIM is available.

### How to reproduce the bug

1. Settings
2. System
3. SIM cards

**Comment by VZuyev** [comment]
![Screenshot_20221030_001](https://user-images.githubusercontent.com/48154777/198874324-bd98fd62-911e-4e11-9f3e-8019a1d8f22c.png)

**Comment by Thaodan** [comment]
The bug should be fixed in the next build.

**Comment by VZuyev** [comment]
Thanks It works.

**Comment by mathieujallois** [comment]
How Can apply fix?

**Comment by VZuyev** [comment]
> How Can apply fix?

Try unzip the archive (including directories) to the /etc/ofono/ directory
[sim2.zip](https://github.com/SailfishOS-SonyXperia/bugs/files/10046710/sim2.zip)
Reboot your phone.

**Comment by mathieujallois** [comment]
ThanksLe 19 nov. 2022 11:32, VZuyev ***@***.***> a écrit :

How Can apply fix?

Try unzip the archive (including directories) to the /etc/ofono/ directory
sim2.zip
Reboot your phone.
