### ISSUE TITLE
[BUG][Kumano][Xperia 5 J9210][SailfishOS-4.4.0.72]: No call sound, no vibration.

### ISSUE THREAD

**Issue by VZuyev** [SailfishOS-SonyXperia/bugs#54]
### Environment

```markdown
- **Platform: Kumano
- **Device: Xperia 5 J9210
- **Sailfish OS Version: 4.4.0.72
- **Kernel version: 4.14
- **Droid-Hal Version: 10
- **Droid-System Version: 10
- **Software binaries version: SW_binaries_for_Xperia_Android_10.0.7.1_r1_v12a_kumano
```

### Previously working on

```markdown
Sailfish OS Version: 4.4.0.68 - there is a ringtone, vibration works
Sailfish OS Version: 4.4.0.72 - no call sound, no vibration.
```

### Description

No call sound, no vibration.

### Symptoms

No call sound, no vibration.

### How to reproduce the bug

1.
2.
3.

**Comment by Thaodan** [comment]
Please provide logs of what happens during the call.

Don't update until the update was whitelisted.

**Comment by VZuyev** [comment]
Please tell me how to do it?

**Comment by VZuyev** [comment]
[Followed this article to get the logs](https://jolla.zendesk.com/hc/en-us/articles/360013910599-Collecting-basic-logs-from-a-Sailfish-device)
[basic-logs-2022-10-29-2322.zip](https://github.com/SailfishOS-SonyXperia/bugs/files/9894554/basic-logs-2022-10-29-2322.zip)
The call was at 23:22

**Comment by Thaodan** [comment]
I'm not sure something might went wrong during the upgrade since the
adaptation repository disappeared during the upgrade since there was no
new repository for that release.

E.g. vibration doesn't work anymore because the notification daemon
doesn't support vibration for the type of hardware in 4.4.0.x.

Please wait till I pushed the update.

**Comment by VZuyev** [comment]
Thanks, back to 4.4.0.68.

**Comment by VZuyev** [comment]
Updated to 4.4.0.72, ringing sound and vibration working.

**Comment by Thaodan** [comment]
Closing as invalid.
