### ISSUE TITLE
[BUG][Kumano][Xperia 5 J9210][SailfishOS-4.4.0.68]: Light sensor, Proximity sensor, Gyro & Accelerometer, Compass does not work

### ISSUE THREAD

**Issue by VZuyev** [SailfishOS-SonyXperia/bugs#55]
### Environment

```markdown
- **Platform: Kumano
- **Device: Xperia 5 J9210
- **Sailfish OS Version: 4.4.0.68
- **Kernel version: 4.14
- **Droid-Hal Version: 10
- **Droid-System Version: 10
- **Software binaries version: SW_binaries_for_Xperia_Android_10.0.7.1_r1_v12a_kumano
```

### Previously working on

```markdown
Light sensor, Proximity sensor, Gyro & Accelerometer, Compass does not work.
```

### Description

Light sensor, Proximity sensor, Gyro & Accelerometer, Compass does not work.

### Symptoms

Light sensor, Proximity sensor, Gyro & Accelerometer, Compass does not work.

### How to reproduce the bug

1. Hardware tests
2. Individual tests
3. Light sensor: Fail
4. Proximity sensor: Fail
5. Gyro & Accelerometer: Fail
6. Compass: Fail

**Comment by Thaodan** [comment]
Is this your earlier install? I assume something went missing during
your upgraded to 4.4.0.72.

Please wait till the update is done building.

**Comment by VZuyev** [comment]
I installed Android 10 (55.1.A.3.49) again. I checked the sensors. They work.
Then I installed the assembly Sailfish 4.4.0.68. The sensors are not working.

**Comment by voidanix** [comment]
Mind if I ask how did you flash the Android 10 images?

Also, if you can you reinstall Android 10, please install [this app](https://github.com/kamgurgul/cpu-info/releases/tag/4.5.0) and go to the sensors tab a bit so they can initialize themselves.

I have no idea if the flash method you used also flashes the persist partition, with the point being that stock Android must create some files in there for sensors to then work under SFOS/AOSP.

**Comment by VZuyev** [comment]
Emma, Newflasher.
Installed cpu-info. Did not help.

**Comment by VZuyev** [comment]
I flashed the persist partition with Newflasher, but that didn't help.

**Comment by VZuyev** [comment]
I installed Android 9 (55.0.A.11.25) again. I checked the sensors. Installed cpuinfo and initialized the sensors.
In Sailfish 4.4.0.68 the sensors are not working.

**Comment by Thaodan** [comment]
You can fix the issue right now by using: `pkcon install hybris-libsensorfw-qt5-binder`.

Please report back after doing so.

**Comment by VZuyev** [comment]
Thank you. The sensors are working.

**Comment by Thaodan** [comment]
VZuyev ***@***.***> writes:

> Thank you. The sensors are working.

Compass too?

**Comment by VZuyev** [comment]
Yes. The compass works.
