### ISSUE TITLE
[BUG][Kumano][Xperia 5 J9210][SailfishOS-4.4.0.68]: Vibration works but not adjustable

### ISSUE THREAD

**Issue by VZuyev** [SailfishOS-SonyXperia/bugs#56]
### Environment

```markdown
- **Platform: Kumano
- **Device: Xperia 5 J9210
- **Sailfish OS Version: 4.4.0.68
- **Kernel version: 4.14
- **Droid-Hal Version: 10
- **Droid-System Version: 10
- **Software binaries version: SW_binaries_for_Xperia_Android_10.0.7.1_r1_v12a_kumano
```

### Previously working on

```markdown
?
```

### Description

Vibration works but not adjustable. Vibration does not respond to duration, repeat, etc.

### Symptoms

Vibration does not respond to duration, repeat, etc.

### How to reproduce the bug

1. Launch the VibrationTest application.
2.
3.

### Additional context

XZ2 SailfishOS-4.4.0.72 this works.

**Comment by Thaodan** [comment]
Vibration isn't adjustable, it is just a feature of the test application.
If this doesn't work it is very likely that it is not a bug in the port.

**Comment by VZuyev** [comment]
Adjustable vibtation works on port XZ2, the test application is working.

**Comment by VZuyev** [comment]
TestVibration works on port XZ2 and Xperia 10 II. Vibration duration is adjustable.
