### ISSUE TITLE
[BUG][Kumano][Xperia 5 J9210][SailfishOS-4.4.0.68]: The Forfernschreiber app crashes when trying to watch a video

### ISSUE THREAD

**Issue by VZuyev** [SailfishOS-SonyXperia/bugs#57]
### Environment

```markdown
- **Platform: Kumano
- **Device: Xperia 5 J9210
- **Sailfish OS Version: 4.4.0.68
- **Kernel version: 4.14
- **Droid-Hal Version: 10
- **Droid-System Version: 10
- **Software binaries version: SW_binaries_for_Xperia_Android_10.0.7.1_r1_v12a_kumano
```

### Previously working on

```markdown
?
```

### Description

The Forfernschreiber app crashes when trying to watch a video

### Symptoms

The Forfernschreiber app crashes when trying to watch a video

### How to reproduce the bug

1.

**Comment by Thaodan** [comment]
Please enable developer mode, start Piepmatz in the terminal app or use ssh.

You can find the instructions in the SailfishOS wiki.

**Comment by VZuyev** [comment]
**Segmentation fault (core dumped)** (When trying to watch a video)
<details>

```
[defaultuser@Xperia5-DualSIM ~]$ harbour-fernschreiber 
[D] unknown:0 - Using Wayland-EGL
library "libGLESv2_adreno.so" not found
library "eglSubDriverAndroid.so" not found
[ 3][t 0][1667333130.369040727][Client.cpp:278][&td_requests]   Begin to wait for updates with timeout 5.000000
[ 3][t 2][1667333130.370366096][Td0.cpp:196][#1][!MultiTd]      Create Td with layer 140, database version 13 and version 37 on 4 threads
[ 3][t 2][1667333130.370471239][Td17.cpp:232][#1][!Td][&td_requests]    Sending update: updateOption {
  name = "version"
  value = optionValueString {
    value = "1.8.3"
  }
}
[ 3][t 2][1667333130.370547771][Td17.cpp:232][#1][!Td][&td_requests]    Sending update: updateAuthorizationState {
  authorization_state = authorizationStateWaitTdlibParameters {
  }
}
[ 3][t 0][1667333130.370580673][Client.cpp:291][&td_requests]   End to wait for updates, returning object 0 0x72ac001ac0
[ 3][t 0][1667333130.371001482][Client.cpp:278][&td_requests]   Begin to wait for updates with timeout 5.000000
[ 3][t 0][1667333130.371083021][Client.cpp:291][&td_requests]   End to wait for updates, returning object 0 0x72ac001c30
[ 3][t 0][1667333130.371271133][Client.cpp:278][&td_requests]   Begin to wait for updates with timeout 5.000000
[ 3][t 2][1667333130.405928611][Td6.cpp:204][#1][!Td][&td_requests]     Receive request 1: setLogVerbosityLevel {
  new_verbosity_level = 2
}
[ 2][t 2][1667333131.373903036][AuthDataShared.cpp:107][#1][!Td]        DcId{2} [auth_key_id:11424177886398840159][state:OK][created_at:1667254918.000000]
[ 2][t 2][1667333131.409090042][Session.cpp:169][#1][!SessionProxy:2:main]      Generate new session_id 15115035927891988486 for auth key 11424177886398840159 for main DC2
[W] unknown:763 - file:///usr/share/harbour-fernschreiber/qml/pages/ChatPage.qml:763: TypeError: Cannot read property 'deleteMessage' of undefined
[ 2][t 3][1667333137.472779035][Session.cpp:169][#1][!SessionProxy:2:download_small#0]  Generate new session_id 4232056790330995711 for auth key 11424177886398840159 for DC-2
[ 2][t 3][1667333137.823992013][AuthDataShared.cpp:107][#1][!Downloader]        DcId{203 external} [auth_key_id:482693872440844187][state:NoAuth][created_at:1667254943.000000]
[ 2][t 3][1667333137.824644804][Session.cpp:169][#1][!SessionProxy:203:download_small#0]        Generate new session_id 10626739897501460122 for CDN auth key 482693872440844187 for DC203
[ 2][t 3][1667333149.177271604][Session.cpp:169][#1][!SessionProxy:2:download#0]        Generate new session_id 15290510836593925820 for auth key 11424177886398840159 for DC-2
[ 2][t 3][1667333149.227154493][Session.cpp:169][#1][!SessionProxy:2:download#1]        Generate new session_id 16787315518433785353 for auth key 11424177886398840159 for DC-2
[ 2][t 3][1667333149.493433237][Session.cpp:169][#1][!SessionProxy:203:download#0]      Generate new session_id 12577480981636831682 for CDN auth key 482693872440844187 for DC203
Segmentation fault (core dumped)
[defaultuser@Xperia5-DualSIM ~]$
```

</details>

EDIT: @Thaodan: I have wrapped the log into a details tag.

**Comment by VZuyev** [comment]
**Segmentation fault (core dumped)** (When trying to watch a video)

**Comment by VZuyev** [comment]
[file.zip](https://github.com/SailfishOS-SonyXperia/bugs/files/9913723/file.zip)

**Comment by VZuyev** [comment]
[root@Xperia5-DualSIM defaultuser]# harbour-videoPlayer Videos/Default/Sailfish_OS_3.0.mp4 
[D] unknown:0 - QML debugging is enabled. Only use this in a safe environment.
error: XDG_RUNTIME_DIR not set in the environment.
[C] unknown:0 - Failed to create display (No such file or directory)
[root@Xperia5-DualSIM defaultuser]#

**Comment by Thaodan** [comment]
@voidanix Have you experienced this one?
I could reproduce it on my test device in csd. The gallery is fine app (both play the same Sailfish 4.0 video).

**Comment by voidanix** [comment]
@Thaodan nope: Fernschreiber, csd video playback and LL's videoPlayer all work fine on 4.4.0.72 with A11 (on 4.14.284).

FYI my device is using droidmedia-0.20211101.0-1, but looking at the [repo on OBS](https://repo.sailfishos.org/obs/nemo:/devel:/hw:/sony:/kumano/latest_aarch64/aarch64/) it could be too new (droidmedia-0.20220716.1-1).

@VZuyev I am attaching the older droidmedia [here](https://cloud.keyedlimepie.org/s/oQP2aHXa28eiD2r), try installing it on your device and see if video works, possibly after a reboot.

**Comment by VZuyev** [comment]
Updated to 4.4.0.72 (sensors are working), droidmedia-0.20220716.1-1. Video is not working.
Installed droidmedia-0.20211101.0-1, the video does not work.

**Comment by VZuyev** [comment]
Sometimes the video works, but after restarting the application (gallery, etc.) it stops working.

**Comment by Thaodan** [comment]
VZuyev ***@***.***> writes:

> Updated to 4.4.0.72 (sensors are working), droidmedia-0.20220716.1-1. Video is not working.

Something is wrong with the droidmedia I've build.

After rebuilding droidmedia I can confirm the issue.
Starting another app such as first gallery and then csd makes the second
application that tries to play a video crash.
