### ISSUE TITLE
[BUG][Kumano][Xperia 5 J9210][SailfishOS-4.4.0.72]: Application Covers Contacts, Calendar, Clock, Notes, Media, Weather have a black color.

### ISSUE THREAD

**Issue by VZuyev** [SailfishOS-SonyXperia/bugs#59]
### Environment

```markdown
- **Platform: Kumano
- **Device: Xperia 5 J9210
- **Sailfish OS Version: 4.4.0.72
- **Kernel version: 4.14
- **Droid-Hal Version: 10
- **Droid-System Version: 10
- **Software binaries version: SW_binaries_for_Xperia_Android_10.0.7.1_r1_v12a_kumano
```

### Previously working on

```markdown
?
```

### Description

Application Covers Contacts, Calendar, Clock, Notes, Media, Weather have a black color. 

### Symptoms

Application Covers Contacts, Calendar, Clock, Notes, Media, Weather have a black color.
Skin color for Contacts, Calendar, Clock, Notes, Media should be atmosphere style color.

### How to reproduce the bug

1. Open application Contacts, Calendar, Clock, Notes, Media, Weather.
2. Hide application.
3.

**Comment by Thaodan** [comment]
Logs from test:
Nov 23 21:42:07 Xperia5-DualSIM dbus-daemon[5431]: dbus-daemon[5431]: [session uid=100000 pid=5431] Activating service name='com.jolla.gallery' requested by ':1.100' (uid=100000 pid=7350 comm="/usr/libexec/mliteremoteaction com.jolla.gallery /" label="u:r:kernel:s0")
Nov 23 21:42:07 Xperia5-DualSIM sailjail[7176]: ignoring argument: -prestart
Nov 23 21:42:07 Xperia5-DualSIM dbus-daemon[5431]: constructing /run/firejail/mnt/privileged: Images,Ambienced,Accounts,Keys ...
Nov 23 21:42:07 Xperia5-DualSIM dbus-daemon[5431]: mounting /run/firejail/mnt/privileged @ /home/defaultuser/.local/share/system/privileged
Nov 23 21:42:07 Xperia5-DualSIM dbus-daemon[5431]: hiding /run/firejail/mnt/privileged
Nov 23 21:42:07 Xperia5-DualSIM jolla-gallery[7390]: [D] unknown:0 - Using Wayland-EGL
Nov 23 21:42:07 Xperia5-DualSIM dbus-daemon[5431]: library "libGLESv2_adreno.so" not found
Nov 23 21:42:07 Xperia5-DualSIM dbus-daemon[5431]: library "eglSubDriverAndroid.so" not found
Nov 23 21:42:08 Xperia5-DualSIM dbus-daemon[5431]: dbus-daemon[5431]: [session uid=100000 pid=5431] Successfully activated service 'com.jolla.gallery'
Nov 23 21:42:14 Xperia5-DualSIM lipstick[5519]: [D] onDestruction:268 - coverActionIndicators destroyed jolla-calendar.desktop
Nov 23 21:42:14 Xperia5-DualSIM booster-generic[5436]: *** signal=17 pid=5436
Nov 23 21:42:14 Xperia5-DualSIM /usr/libexec/mapplauncherd/booster-generic[5436]: warning: Daemon: sending exit(0) to invoker(7175)
Nov 23 21:42:16 Xperia5-DualSIM dbus-daemon[5431]: dbus-daemon[5431]: [session uid=100000 pid=5431] Activating service name='com.jolla.calendar.ui' requested by ':1.103' (uid=100000 pid=7420 comm="/usr/libexec/mliteremoteaction com.jolla.calendar." label="u:r:kernel:s0")
Nov 23 21:42:16 Xperia5-DualSIM sailjail[7354]: ignoring argument: -prestart
Nov 23 21:42:16 Xperia5-DualSIM dbus-daemon[5431]: constructing /run/firejail/mnt/privileged: Accounts,Keys,Calendar,Contacts,Images,eas-sailfish ...
Nov 23 21:42:16 Xperia5-DualSIM dbus-daemon[5431]: mounting /run/firejail/mnt/privileged @ /home/defaultuser/.local/share/system/privileged
Nov 23 21:42:16 Xperia5-DualSIM dbus-daemon[5431]: hiding /run/firejail/mnt/privileged
Nov 23 21:42:16 Xperia5-DualSIM jolla-calendar[7463]: [D] unknown:0 - Using Wayland-EGL
Nov 23 21:42:16 Xperia5-DualSIM dbus-daemon[5431]: library "libGLESv2_adreno.so" not found
Nov 23 21:42:16 Xperia5-DualSIM dbus-daemon[5431]: library "eglSubDriverAndroid.so" not found
Nov 23 21:42:17 Xperia5-DualSIM dbus-daemon[5431]: dbus-daemon[5431]: [session uid=100000 pid=5431] Successfully activated service 'com.jolla.calendar.ui'
Nov 23 21:42:17 Xperia5-DualSIM jolla-calendar[7463]: [W] unknown:0 - DeclarativeCoverWindow: You should be calling QQuickWindow::setDefaultAlphaBuffer(true) before creating windows. Failing to do so may result in suboptimal performance.
Nov 23 21:42:17 Xperia5-DualSIM jolla-calendar[7463]: [W] unknown:0 - DeclarativeCoverWindow: You also won't have cover transparency.
Nov 23 21:42:18 Xperia5-DualSIM lipstick[5519]: [D] onCompleted:264 -
coverActionIndicators created jolla-calendar.desktop
