### ISSUE TITLE
[BUG] Kumano fails to suspend

### ISSUE THREAD

**Issue by voidanix** [SailfishOS-SonyXperia/bugs#8]
`/sys/power/wake_lock` was empty and `/d/wakeup_sources` kept reporting `qcom,qup_uart@c8c000` and `DIAG_WS` as the most frequent wakeup sources (in the neighbourhood of 200000-300000 `event_count`s), making sleep fail with noirq errors.

Kumano which uses SM8150 requires https://github.com/sonyxperiadev/kernel/pull/2516 (or https://github.com/sonyxperiadev/kernel/pull/2517 in case a jump to A12/4.19 base will be considered) for it to go into deep slumber.

See also:
- https://github.com/sailfishos-sony-tama/main/issues/105

**Comment by Thaodan** [comment]
Merged in:
- https://github.com/mer-hybris/android_kernel_sony_msm/pull/118
