### ISSUE TITLE
[BUG][Kumano][Xperia 5 J9210][SailfishOS-4.5.0.19]: No start Angelfish

### ISSUE THREAD

**Issue by VZuyev** [SailfishOS-SonyXperia/bugs#82]
### Environment

```markdown
- **Platform: Kumano
- **Device: Xperia 5 J9210
- **Sailfish OS Version: 4.5.0.19
- **Kernel version: 4.14
- **Droid-Hal Version: 10
- **Droid-System Version: 10
- **Software binaries version: SW_binaries_for_Xperia_Android_10.0.7.1_r1_v12a_kumano
```

### Previously working on

```markdown
?
```

### Description

No start Angelfish.

### Symptoms

No start Angelfish.

[defaultuser@Xperia5-DualSIM ~]$ angelfish
library “libGLESv2_adreno.so” not found
library “eglSubDriverAndroid.so” not found
angelfish: symbol lookup error: /opt/qt5/lib64/qt5/plugins/wayland-graphics-integration-client/libqt-plugin-wayland-egl.so: undefined symbol: eglCreatePlatformWindowSurface

### How to reproduce the bug

1.
2.
3.

### Additional context

[defaultuser@Xperia5-DualSIM ~]$ angelfish
library “libGLESv2_adreno.so” not found
library “eglSubDriverAndroid.so” not found
angelfish: symbol lookup error: /opt/qt5/lib64/qt5/plugins/wayland-graphics-integration-client/libqt-plugin-wayland-egl.so: undefined symbol: eglCreatePlatformWindowSurface

**Comment by VZuyev** [comment]
https://forum.sailfishos.org/t/developer-announcement-qt-5-15-available-for-app-developer-testing/15105/100

**Comment by Thaodan** [comment]
Not a bug. I don't support Anglefish. However the update should fix it.

Public builds don't contain newer libhybris, will change with the next update.
