### ISSUE TITLE
[BUG][Kumano][Xperia 1 J9110][SailfishOS-4.4.0.72]: WIFI doesn't work after initial re-flashing

### ISSUE THREAD

**Issue by SamRocknrolla** [SailfishOS-SonyXperia/bugs#84]
### Environment

```markdown
- **Platform:** Kumano
- **Device:** J9110
- **Sailfish OS Version:** 4.4.0.72
- **Kernel version:** 4.14
- **Droid-Hal Version:** 11
- **Droid-System Version:** 11
- **Software binaries version:** SW_binaries_for_Xperia_Android_10.0.7.1_r1_v12a_kumano.img, SW_binaries_for_Xperia_Android_10.0.7.1_r1_v11a_kumano.img, SW_binaries_for_Xperia_Android_10.0.7.1_r1_v10a_kumano.img
```

### Previously working on

```markdown
N/A
```

### Description

WIFI connection unavailable under Sailfish OS. There are no active wlan interfaces. Dmesg log include messages, that wlan driver has been loaded without errors.

### Symptoms

User can't enable WLAN interface in GUI

### How to reproduce the bug

1. Boot to fastboot mode and re-flash Sailfish in accordance with instruction
2. Pass setup at first boot of OS
3. Open  Settings->WIFI  
    *Expected:* WLAN interface should be available for swith ON/OFF
    *Actual:* WLAN page is empty.

  

### Additional context

Dmesg log diesn't include any errors with wlan drivers. 
Wlan driver loaded without errors.

*Android version info* 
Kernel version: 4.14.190-perf+

*Firmware*
855-sm8150.gen.prodQ-00043-49

**Comment by Thaodan** [comment]
Which stock Android was installed before?

**Comment by SamRocknrolla** [comment]
I didn't downgrade Android from v11 to v10 before Sailfish re-flasing. Please close.

**Comment by Thaodan** [comment]
Closed, see comment above.
